#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Assemble jssrc/*.js into src/pyside6_webusb/_polyfill_bundle.py.

The polyfill is authored as plain JavaScript under ``jssrc/`` (so it can be linted and
run under Node) and shipped inside the wheel as a *Python module*: that works on every
platform, including Android/PySide6 deployments that do not bundle non-.py data files.

    python scripts/build_polyfill.py            # (re)generate the bundle
    python scripts/build_polyfill.py --check    # exit 1 if the bundle is stale

tests/test_polyfill_bundle.py runs ``--check`` so a forgotten rebuild fails CI.
"""
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JS_DIR = os.path.join(ROOT, "jssrc")
OUT = os.path.join(ROOT, "src", "pyside6_webusb", "_polyfill_bundle.py")

_BLOCK_COMMENT = re.compile(r"^[ \t]*/\*.*?\*/[ \t]*\n", re.S | re.M)


def _strip(js):
    """Drop whole-line ``//`` comments and block comments that start a line.

    Inline ``/*MARKER*/`` comments (config/library slots) are deliberately preserved.
    """
    js = _BLOCK_COMMENT.sub("", js)
    kept = []
    for line in js.split("\n"):
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue
        kept.append(line.rstrip())
    return "\n".join(kept)


def assemble():
    names = sorted(n for n in os.listdir(JS_DIR) if re.match(r"^\d\d_.*\.js$", n))
    parts = []
    for n in names:
        with open(os.path.join(JS_DIR, n), encoding="utf-8") as f:
            parts.append(_strip(f.read()))
    body = "\n".join(parts)
    return "(function () {\n'use strict';\n" + body + "\n})();\n", names


def render(js, names):
    digest = hashlib.sha256(js.encode("utf-8")).hexdigest()
    lines = js.split("\n")
    out = [
        "# -*- coding: utf-8 -*-",
        '"""GENERATED by scripts/build_polyfill.py from jssrc/*.js -- DO NOT EDIT BY HAND.',
        "",
        "Sources: " + ", ".join(names),
        '"""',
        "",
        "JS_SHA256 = %r" % digest,
        "",
        "POLYFILL_JS_TEMPLATE = \"\\n\".join((",
    ]
    for line in lines:
        out.append("    %r," % line)
    out.append("))")
    out.append("")
    return "\n".join(out)


def main(argv):
    js, names = assemble()
    text = render(js, names)
    if "--check" in argv:
        try:
            with open(OUT, encoding="utf-8") as f:
                current = f.read()
        except OSError:
            current = ""
        if current != text:
            print("STALE: %s is out of date; run scripts/build_polyfill.py" % OUT)
            return 1
        print("polyfill bundle is up to date")
        return 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s (%d bytes of JS, %d lines)" % (OUT, len(js), js.count("\n") + 1))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
